spring.application.name=rfq-auction-backend
spring.datasource.url=jdbc:mysql://localhost:3306/british_auction?useSSL=false&serverTimezone=UTC

# Your MySQL username (default is root)
spring.datasource.username=root

# Your MySQL password
spring.datasource.password=426200

# This tells Hibernate (JPA) to auto-create/update tables from our Entity classes
# "update" means: if table doesn't exist, create it. If it exists, update columns.
spring.jpa.hibernate.ddl-auto=update

# This makes Hibernate print the SQL it generates — useful for debugging
spring.jpa.show-sql=true

# Tells JPA we are using MySQL database
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Our Spring Boot server runs on port 8080
server.port=8080